added controller actions and custom routes to match frontend api.serv…
afteralec/gifmemore-backend pull request #5
Opened 2020-09-26 22:30 UTC by Bakugou808

…ices file

2020-09-27 04:02 UTC, afteralec commented on app/controllers/carts_controller.rb
> +    def addItem
`CartsController#addItem` looks like it's reversed with `removeItem`; i.e. validating for record.destroy and will remove items

Do we need a custom route to add items? I think we could use PATCH to Cart to add and remove items by sending a complete picture of the current cart from the front end to be more robust

2020-09-27 04:03 UTC, afteralec commented on app/controllers/orders_controller.rb
> +    def orderHistory
I think this could be an `index` action using the current_user defined by the JWT authorization context instead and would be less custom; let me know what you think

2020-09-27 04:06 UTC, afteralec commented on app/models/order.rb
> +  def addToOrder(itemIds)
This syntax looks incorrect, do we have => notation in Ruby inside a function call like this? It looks like a javascript arrow function; let me know if I'm off here

Probably should be more like:

item_ids.each { |item_id| ItemOrder.create(order: self, item_id: item_id) }

2020-09-27 04:07 UTC, afteralec commented on config/routes.rb
> +  get '/orders/user_history/:user_id', to: 'orders#orderHistory'
Per above notes, I think we could use standard RESTful routes from the api/v1 path for these actions; let's review this Monday

2020-09-27 04:07 UTC, afteralec requested changes
Please see my in-line comments in each file; I'm requesting that we review this together before merging it into main branch

2020-09-27 04:08 UTC, afteralec commented on app/controllers/carts_controller.rb
> +    def addItem
Oops; I'll make sure to add comment to a line BELOW the code I'm referencing in the future

2020-09-27 04:09 UTC, afteralec commented on app/controllers/orders_controller.rb
> +    def orderHistory
See my oops above

2020-09-27 04:09 UTC, afteralec commented on app/models/order.rb
> +  def addToOrder(itemIds)
See my oops above

2020-09-27 04:09 UTC, afteralec commented on config/routes.rb
> +  get '/orders/user_history/:user_id', to: 'orders#orderHistory'
See my oops above, there are more routes below line 3 that I have questions about

2020-09-27 19:23 UTC, Bakugou808 commented on app/controllers/carts_controller.rb
> +    def addItem
I think we do; since the cart only has a user reference as an attribute, we'd need to remove/add from the item_carts Join table. Unless you were thinking of something like:

@cart.item_carts = current cart 

but I'm not familiar if that will actually update the join table properly. I figured this was the clearest and most direct way besides building out a post and delete within an items_carts controller. 

How were you thinking of updating the cart via PATCH?

2020-09-27 19:24 UTC, Bakugou808 commented on app/controllers/carts_controller.rb
> +    def addItem
oh and they are definitely swapped. good eye!

2020-09-27 19:33 UTC, Bakugou808 commented on app/models/order.rb
> +  def addToOrder(itemIds)
oh no thats just Ruba-Script. It just came out. New update from last week...


Jk, total syntax error. lol. Lets fix that pre-merge.

2020-09-27 19:36 UTC, Bakugou808 commented on config/routes.rb
> +  get '/orders/user_history/:user_id', to: 'orders#orderHistory'
yea lets review Monday.

2020-09-28 16:40 UTC, afteralec approved these changes

2020-09-28 16:45 UTC, merged